version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      LEXICON_PATH: /opt/program/data/lexica
      DB_CONN_STRING: "host=db port=5432 user=postgres dbname=liwords password=pass sslmode=disable"
      SECRET_KEY: jqxztripletriple
      DEBUG: 1
      NATS_URL: nats://nats:4222
    volumes:
      - .:/opt/program:rw
    command: sh -c "go run cmd/liwords-api/*.go"
    networks:
      - aeronet
    ports:
      - "8001:8001"
    labels:
      - "traefik.http.routers.liwords.rule=Host(`liwords.localhost`) && PathPrefix(`/twirp/liwords.`)"
      - "traefik.http.routers.liwords.entrypoints=web"
      - "traefik.http.services.liwords.loadbalancer.server.port=8001"
      - traefik.enable=true

  socket:
    build:
      context: ../liwords-socket
      dockerfile: Dockerfile-dev
    environment:
      SECRET_KEY: jqxztripletriple
      DEBUG: 1
      NATS_URL: nats://nats:4222
    volumes:
      - ../liwords-socket:/opt/program:rw
    command: sh -c "go run cmd/socketsrv/*.go"
    networks:
      - aeronet
    ports:
      - "8087:8087"
    labels:
      - "traefik.http.routers.liwords-socket.rule=Host(`liwords.localhost`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.liwords-socket.entrypoints=web"
      - "traefik.http.services.liwords-socket.loadbalancer.server.port=8087"
      - traefik.enable=true

  proxy:
    image: "traefik:v2.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - aeronet

  nats:
    image: "nats"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - aeronet

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: liwords
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - aeronet
# This runs too slowly inside Docker. Why?
# frontend:
#   build:
#     context: .
#     dockerfile: Dockerfile-fe
#   volumes:
#     - ./liwords-ui:/opt/liwords-ui
#   working_dir: /opt/liwords-ui
#   command: npm start
#   # Need the following else the frontend quits immediately:
#   stdin_open: true
#   networks:
#     - aeronet
#   labels:
#     - "traefik.http.routers.xwordclub-fe.rule=Host(`vm.xword.club`)"
#     - "traefik.http.services.xwordclub-fe.loadbalancer.server.port=3000"
#     - traefik.enable=true
networks:
  aeronet:
    driver: bridge
volumes:
  pg-data-volume:
    external: false
