version: 2
jobs:
  build_socket_srv:
    environment:
      LEXICON_PATH: /opt/lexica/
    docker:
      - image: golang:alpine
    working_directory: /opt/liwords
    steps:
      - checkout
      - run:
          name: Install build-base (for tests)
          command: apk update && apk upgrade && apk add build-base

      - run: mv /opt/liwords/data/lexica $LEXICON_PATH
      - run: cd cmd/socketsrv && go build # persist executable to workspace for deploy step
      - run: go test ./...

  build_fe:
    working_directory: /opt/liwords
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: cd liwords-ui && npm install
      - run: cd liwords-ui && npm run test
      - run: cd liwords-ui && npm run build

    # Later persist to workspace for deploy step.

workflows:
  version: 2
  build_app:
    jobs:
      - build_socket_srv
      - build_fe
