version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build_socket_srv:
    environment:
      LEXICON_PATH: /opt/lexica/
    docker:
      - image: golang:alpine
    working_directory: /opt/liwords
    steps:
      - checkout
      - run:
          name: Install build-base (for tests) and bash (for slack notifier)
          command: apk update && apk upgrade && apk add bash build-base

      - run: mv /opt/liwords/data/lexica $LEXICON_PATH
      - run: cd cmd/socketsrv && go build # persist executable to workspace for deploy step
      - run: go test ./...
      - slack/status:
          webhook: "${SLACK_WEBHOOK}"

  build_fe:
    working_directory: /opt/liwords
    docker:
      - image: node:alpine
    steps:
      - checkout
      - run: apk add bash
      - run: cd liwords-ui && npm install
      - run: cd liwords-ui && npm run test
      - run: cd liwords-ui && npm run build
      - slack/status:
          webhook: "${SLACK_WEBHOOK}"

    # Later persist to workspace for deploy step.

workflows:
  version: 2
  build_app:
    jobs:
      - build_socket_srv
      - build_fe
